### ISSUE TITLE
API per registrar crides

### ISSUE THREAD

**Issue by jordidh** [CodeBiting/onion-cargo-loading-service#11]
Objectiu: Crear una API (GET, POST, PUT, DELETE) per ser consultada per un usuari administrador i que pugui consultar les crides fetes per un client a les API públiques i crear/modificar/esborrar crides fetes. 
S'ha de registrar cada crida de les API públiques realitzada per cada client. 
L'objectiu d'aquest registre és tenir estadístiques de temps de resposta, resultat, detectar crides amb error i saber quan facturar a cada client.

les dades que s'han de guardar per cada crida són:

- Data i hora de la crida
- Origen (IP, port, ...)
- Destí (URL de la crida)
- Mètode (POST, PUT, ...)
- Dades (body de la crida)
- Identificador únic de la crida
- Resultat (http status) de la crida (s'ha de posar un cop retorna)
- Dades resultants de la crida

Passos:

- [x] Identificar cada crida de la API pública amb un ID únic que es passi a totes les crides internes i es deixin logs amb aquest ID per poder seguir en tot el flux d'execució.
- [x] Implementar l'API
- [x] Registrar a cada API la informació de la crida

**Comment by Luisitodelcastillo** [comment]
@jordidh modificació de **let requestId = req.headers["x-request-id"]**  a **let requestId = req.requestId** , a container.js,  per poder visualitzar el uniqid al ApiResult.
També al generador de id al middleware ha sigut lleugerament modificat, modificació de **next();** a **next(null, req.requestId);** 
Resultat:
![image](https://user-images.githubusercontent.com/115095814/228202199-bc187100-56cf-46a0-b29e-956e307eed90.png)

Així et sembla bé?
