### ISSUE TITLE
Implementació d'una interfície d'usuari d'administració per consultar clients, contenidors i registres

### ISSUE THREAD

**Issue by jordidh** [CodeBiting/onion-cargo-loading-service#31]
## Objectiu 

L'objectiu d'aquesta interfície és que es pugui fer manteniment de l'aplicació i determinar el número de crides que ha fet cada client, o sigui, el número de registres que existeixen pel client en la taula "register" dins d'un període de temps.
La UI ha d'estar a dins de la ruta `/ui/v1/`, per separar-ho més de la API canviar la ruta de les api de `/v1/` a `/api/v1/`.

## Solució

Implementar les següents pantalles:

1. Consulta de clients: s'ha de poder buscar per codi, i ordenades per data d'inici o codi. S'ha de mostrar el número de contenidors de cada client i el número de registres acumulats en total.
2. Activació/desactivació de clients: s'ha de poder editar un client o activar-lo/desactivar-lo i canviar les dates d'inici i fi.
3. Consulta de contenidors que té un client.
4. Consulta de registres de crides d'un client concret dins d'un període de temps.

## Alternatives d'implementació

1. S'ha de fer la interfície fent servir PUG.
2. Opcionalment es pot mirar d'integrar components javascript per mostrar les dades per facilitar la consulta i edició, per exemple, <https://gridjs.io/>, <https://react-table.tanstack.com/>, <https://www.ag-grid.com/>

Enllaços d'interès: <https://blog.logrocket.com/5-open-source-javascript-datagrids/>

**Comment by Arcedo** [comment]
A l'hora de filtrar per qualsevol camp s'hi pot fer per filtratges de l'ag-grid, sense haver d'implementar res més.

**Comment by jordidh** [comment]
## Escenaris de treball amb la interfície d'usuari d'administració

Gestió de clients:

- [ ] L'usuari ha de poder veure tots els clients amb el camp deleted_at a null amb el número de contenidors i número de registres
- [ ] L'usuari no ha de poder veure els clients amb el camp deleted_at diferent de null
- [ ] L'usuari ha de poder recuperar els clients de forma paginada
- [ ] L'usuari ha de poder crear un client omplint totes les dades
- [ ] L'usuari ha de poder crear un client sense data d'inici, de finalització, ni token, ni notes
- [ ] L'usuari no ha de poder crear un client si no proporciona el camp code o active
- [ ] L'usuari no ha de poder crear un client amb un codi que ja existeixi
- [ ] L'usuari ha de poder modificar un client canviant el code, les dates d'inici i fi, l'active, el tiken i les notes
- [ ] L'usuari no ha de poder modificar un client amb un codi que ja existeixi
- [ ] L'usuari ha de poder eliminar (MARCAR EL CAMP DELETED_AT) un client
- [ ] L'usuari si crea un client i el codi ja existeix però amb un client amb el deleted_at esborrat ha de demanar si es vol reactivar el client, si diu que si es restaura (deleted_at a null) sinó s'ha de donar error per codi repetit.

Gestió de containers:

- [ ] L'usuari ha de poder veure tots els contenidors amb el camp deleted_at a null
- [ ] L'usuari no ha de poder veure els contenidors amb el camp deleted_at diferent de null
- [ ] L'usuari ha de poder recuperar els contenidors de forma paginada
- [ ] L'usuari ha de poder crear un contenidor omplint totes les dades
- [ ] L'usuari ha de poder crear un contenidor sense descripció
- [ ] L'usuari no ha de poder crear un contenidor si no proporciona tots els camps excepte el de descripció
- [ ] L'usuari ha de poder crear un contenidor amb un codi repetit
- [ ] L'usuari ha de poder modificar un contenidor canviant tots els camps, inclòs el code
- [ ] L'usuari ha de poder modificar un contenidor amb un codi que ja existeixi
- [ ] L'usuari ha de poder eliminar (MARCAR EL CAMP DELETED_AT) un contenidor
- [ ] L'usuari si crea un contenidor i el codi ja existeix però amb un contenidor amb el deleted_at esborrat NO ha de demanar si es vol reactivar

Gestió de registres:

- [ ] L'usuari ha de poder recuperar els registres de forma paginada
